apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyaltyreward
  labels:
    app: loyaltyreward
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyaltyreward
  template:
    metadata:
      labels:
        app: loyaltyreward
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "10255"
    spec:
      containers:
      - image: "docker.io/pscoec4f/loyaltyreward:0.0.2-SNAPSHOT"
        name: loyaltyreward
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
        - name: PROMO_GROUP
          value: "loyaltycustomers"
        - name: PROMO_PRODUCT
          value: "834954"
        - name: PROMO_PRODUCT_QUANTITY
          value: "6"
---
apiVersion: v1
kind: Service
metadata:
  name: loyaltyreward
  labels:
    app: loyaltyreward
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: loyaltyreward
  type: ClusterIP